# Generated by Django 3.2.7 on 2021-09-29 20:11

from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='Backdrops',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', imagekit.models.fields.ProcessedImageField(upload_to='wedding/profile_backdrop/', verbose_name='배경사진')),
            ],
        ),
        migrations.CreateModel(
            name='Mc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='이름')),
                ('title', models.CharField(max_length=20, verbose_name='호칭')),
                ('description', models.TextField(verbose_name='설명')),
                ('profile_photo', models.ImageField(upload_to='wedding/profile_photo/', verbose_name='프로필사진')),
                ('profile', models.TextField(blank=True, verbose_name='프로필')),
                ('profile_backdrop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wedding.backdrops')),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
        migrations.CreateModel(
            name='Youtube',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=20, verbose_name='유튜브일련번호')),
                ('wedding_mc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wedding.mc')),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', imagekit.models.fields.ProcessedImageField(upload_to='wedding/gallery/', verbose_name='사회자사진')),
                ('wedding_mc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wedding.mc')),
            ],
        ),
    ]
