# Generated by Django 3.2.7 on 2021-09-30 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0002_auto_20210930_1637'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bride', models.CharField(blank=True, max_length=20, verbose_name='신부님 성함')),
                ('groom', models.CharField(blank=True, max_length=20, verbose_name='신랑님 성함')),
                ('bride_phone', models.CharField(blank=True, max_length=20, verbose_name='신부님 연락처')),
                ('groom_phone', models.CharField(blank=True, max_length=20, verbose_name='신랑님 연락처')),
                ('wedding_date', models.DateTimeField(blank=True, null=True, verbose_name='본식 날짜,시간')),
                ('wedding_place', models.CharField(blank=True, max_length=50, verbose_name='본식 장소')),
                ('wedding_reception', models.BooleanField(default=False, verbose_name='2부 진행')),
                ('email_addr', models.EmailField(blank=True, max_length=254, verbose_name='메일주소')),
                ('wish_mc', models.CharField(blank=True, max_length=100, verbose_name='희망 사회자')),
                ('customer_memo', models.TextField(blank=True, verbose_name='고객 메모')),
                ('staff_memo', models.TextField(blank=True, verbose_name='스탭 메모')),
                ('create_date', models.DateTimeField(verbose_name='문의시간')),
            ],
        ),
    ]
