# Generated by Django 3.2.7 on 2021-09-30 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0003_cast'),
    ]

    operations = [
        migrations.AddField(
            model_name='cast',
            name='officiator',
            field=models.BooleanField(default=False, verbose_name='주례'),
        ),
    ]
